### ISSUE TITLE
Need for ways to express different config_registers definition for variants

### ISSUE THREAD

**Issue by elfmimi** [ch32-rs/wchisp#11]
for example, config_registers definition in 0x11-CH55x.yaml is currently correct only for CH559.

**Comment by andelf** [comment]
Yes. This needs to be fixed.

A hack I use is https://github.com/ch32-rs/wchisp/blob/main/devices/0x12-CH54x.yaml

https://github.com/ch32-rs/wchisp/blob/aedf69aa685f57db1d623d828920f06277471505/devices/0x12-CH54x.yaml#L10

**Comment by andelf** [comment]
Close this.
To see how to express different config_registers definitions for variants:
https://github.com/ch32-rs/wchisp/blob/main/devices/0x13-CH57x.yaml
