### ISSUE TITLE
Add Cargo.lock

### ISSUE THREAD

**Issue by kalebpace** [ch32-rs/wchisp#32]
I am currently trying to build a Nix package for this project. Since it lacks a Cargo.lock, it is difficult to get reproducible builds. 

It would be nice to have this included as per the [Cargo Book](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html)

Thanks!

**Comment by andelf** [comment]
Agreed, binary package should have a Cargo.lock.

**Comment by kalebpace** [comment]
Perfect, thanks! 

https://github.com/kalebpace/rtthread-binary-clock-ch32v208w-r0/blob/ec6034cd9ffc921d3a0759eaac4bbbe2c789a045/nix/wchisp/default.nix
