### ISSUE TITLE
It works well,add ch549 in README

### ISSUE THREAD

**Issue by syx-413** [ch32-rs/wchisp#45]
Thanks for your develop,I can use bash not WCHIspStudio which is better for me. Thanks again!!!❤️❤️❤️
![image](https://github.com/ch32-rs/wchisp/assets/104879935/4fb0b89a-cf2f-4b4f-9873-04c5cdd4912d)

**Comment by froscon2024** [comment]
Could you tell or link to what exact PCB hardware you tested it with?

**Comment by syx-413** [comment]
[This](https://gitee.com/verimaker/vm-wch-51-evb-ch549evb/blob/master/doc/Schematic_VeriMake_CH549DB_v1_0_0_20220123.pdf) ,like this [forums show](https://verimake.com/d/19-ch549-51)
