### ISSUE TITLE
Is flash programming over USART1 supported?

### ISSUE THREAD

**Issue by Thom-de-Jong** [ch32-rs/wchisp#55]
I would like to know the status of programming over the serial interface.

Is it possible? If not, is support planned?
Are there any Linux CLI tools that have this function?
I have not been able to get it to work, even using the official WCHISP_Tool from WCH...

**Comment by Thom-de-Jong** [comment]
#56

**Comment by basilhussain** [comment]
This issue can be closed now that serial support has been implemented in release v0.3.0. 😄
